### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by asrod** [luckydonald/pbft#11]
**docker-compose build**
When all steps(18/18) are done, the error happens. Can someone help me fix this problem?

**Comment by luckydonald** [comment]
Could you please specify your system: os & docker version

And also the full command and output?

**Comment by asrod** [comment]
Ubuntu 18.04.1
Docker 18.09.1

**output**：
Step 1/18 : FROM node
 ---> 7d3b4aa10229
Step 2/18 : EXPOSE 8000
 ---> Using cache
 ---> 28f39fc4ab92
Step 3/18 : RUN mkdir -p /app/code
 ---> Using cache
 ---> f2fc16d0401d
Step 4/18 : WORKDIR /app/
 ---> Using cache
 ---> f41246a2fc40
Step 5/18 : RUN npm config set prefix /app/libs
 ---> Using cache
 ---> 218016378bf0
Step 6/18 : ENV PATH /app/libs/bin:$PATH
 ---> Using cache
 ---> c56694c1826d
Step 7/18 : RUN echo $PATH
 ---> Using cache
 ---> 408f0f1822b2
Step 8/18 : RUN npm install -g bower
 ---> Using cache
 ---> fe352659c0bb
Step 9/18 : RUN npm install -g http-server
 ---> Using cache
 ---> 2ea10d870b07
Step 10/18 : ADD package.json /app
 ---> Using cache
 ---> 9a75c9e13124
Step 11/18 : ADD .bowerrc /app
 ---> Using cache
 ---> e6d8acf576a4
Step 12/18 : ADD bower.json /app
 ---> Using cache
 ---> c184c543c188
Step 13/18 : RUN bower install --allow-root
 ---> Using cache
 ---> ca76b7b85fbb
Step 14/18 : ADD ./src /app/src
 ---> Using cache
 ---> ccc0c0fb37c8
Step 15/18 : ADD ./example /app/example
 ---> Using cache
 ---> 8058c0c8423a
Step 16/18 : COPY ./entrypoint.sh /entrypoint.sh
 ---> Using cache
 ---> 8a97d66de615
Step 17/18 : RUN chmod +x /entrypoint.sh
 ---> Using cache
 ---> 7a17e2ce7814
Step 18/18 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> a15f1624d558
Successfully built a15f1624d558
Successfully tagged pbft_web_static:latest
Building postgres_browser
ERROR: Cannot locate specified Dockerfile: Dockerfile

**Comment by asrod** [comment]
Sorry, I  forgot to clone submodule of this project
right command：git clone --recursive https://github.com/luckydonald/pbft.git

**Comment by luckydonald** [comment]
I forgot to add that to the readme.
