### ISSUE TITLE
please help me 

### ISSUE THREAD

**Issue by hossamsamy007** [luckydonald/pbft#12]
every thing is up but there is no motion or data i can take from the program what ican do am making auditing on the code so please help me to make this better

**Comment by luckydonald** [comment]
First point would to look at the logs, and see if you find something unusual.
Also read through #9 and other issues, if you can gather something helpful there.

I'm not very involved with this any longer, so I can't help you in detail anyway.

**Comment by luckydonald** [comment]
Closed as a duplicate.
