### ISSUE TITLE
Implement PBFT in blockchain instead of Proof of work

### ISSUE THREAD

**Issue by chandankuiry** [luckydonald/pbft#8]
If I want to implement PBFT algorithm instead of proof of work, How can I implement this pbft algorithm?
lets take this tutorial http://adilmoujahid.com/posts/2018/03/intro-blockchain-bitcoin-python/ . How can i implement simple PBFT which can handle 5,6 nodes ?

Thank you

**Comment by luckydonald** [comment]
<sup><sup><sup>`b` `l` `o` `c` `k` `c` `h` `a` `i` `n`.</sup></sup></sup>
Sorry, this project has reached completion.
Therefore I can't provide you code assistence.

However, if your question is how to scale them to more nodes, use
```bash
$ docker-compose scale node={number of nodes}
```

**Comment by luckydonald** [comment]
If you get something working, please share though.
